#!/bin/sh
#
# Wrapper over the real netresolve compatibility wrapper that can be run
# within the source tree.

dirname=$(dirname $0)

export LD_LIBRARY_PATH="$dirname/.libs"
source "$dirname/tools/wrapresolve.in"
